# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171115_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
